// Generated by CoffeeScript 1.3.3
(function() {
  var Project, User, persist, type;

  exports.persist = persist = require("persist");

  exports.type = type = persist.type;

  exports.Project = Project = persist.define("project", {
    data: type.STRING
  });

  exports.User = User = persist.define("user", {
    email: type.STRING,
    password: type.STRING
  });

  exports.db = function(cb) {
    return persist.connect({
      driver: 'sqlite3',
      filename: 'db/dev.db',
      trace: true
    }, cb);
  };

}).call(this);
